# -*- coding: utf-8 -*-
"""Programación 3 - Trabajos Prácticos - Unidad 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuI6q1KAUbXao_KObdVjGox1Xl4CUbCm

**Ejercicio 1:** Solicitar al usuario que ingrese su nombre y mostrar por pantalla
"""

nom=str(input("Ingrese su nombre: "))
print("Su nombre es:",nom)

"""**Ejercicio 2:** Calcular el área y el perímetro de un rectángulo, para lo cual se deben ingresar el valor del lado A y el valor del lado B."""

ladoA=float(input("Ingrese la longitud del lado A: "))
ladoB=float(input("Ingrese la longitud del lado B: "))
perim=ladoA*2+ladoB*2
area=ladoA*ladoB
print("El perímetro del rectángulo es:",perim)
print("El área del rectángulo es:",area)

"""**Ejercicio 3:** Solicitar al usuario que ingrese su edad, saludarlo y decirle que edad tendría dentro de 730 días."""

edad=int(input("Ingrese su edad: "))
dos_anios=edad+2
print("¡Hola! Tu edad dentro de 730 días será:",dos_anios)

"""**Ejercicio 4:** La cuota de un club deportivo incrementa su costo todos los meses
en un 2% respecto del mes anterior. Si el valor de la cuota en enero es de $1000, determinar el valor para el mes de abril.
"""

cuota=1000
for i in range(3):
  incremento=cuota*0.02
  cuota=cuota+incremento
print("El valor de la cuota para el mes de abril será de: $",cuota)

"""**Ejercicio 5:** Ingresar dos números y devolver el mayor de ellos."""

numA=float(input("Ingrese el primer número: "))
numB=float(input("Ingrese el segundo número: "))
if numA>numB:
  print("El número mayor es el:",numA)
elif numA<numB:
  print("El número mayor es el:",numB)
else:
  print("Los números son iguales.")

"""**Ejercicio 6:** Solicitar al usuario que ingrese un número y determinar si es par o impar.

"""

num=float(input("Ingrese el número: "))
if num%2==0:
  print("El número ingresado es par.")
else:
  print("El número ingresado es impar.")

"""**Ejercicio 7:** Se desea calcular el salario neto semanal de un trabajador en función del número de horas trabajadas en la semana y el precio que se paga por hora:
*   Las primeras 35 horas se pagan a precio normal.
*   Las horas que pasen de 35 se pagan a 1.5 veces la tarifa normal


"""

precio=float(input("Ingrese el precio pagado por hora: "))
horas=int(input("Ingrese la cantidad de horas trabajadas: "))
horasextra=0
if horas>35:
  horasextra=horas-35
  salarioextra=horasextra*precio*1.5
  print(salarioextra)
  salario=35*precio+salarioextra
else:
 salario=horas*precio
print("El salario neto del trabajador por",horas,"trabajadas es de: $",salario)

"""**Ejercicio 9:** Dados N números reales indicar cuántos positivos hay en la lista."""

N=int(input("Ingrese la cantidad de números para la lista: "))
lista=[]
for i in range(N):
  num=float(input("Ingrese un número: "))
  lista.append(num)
pos=0
for i in range(N):
  if lista[i]>0:
    pos=sum(1 for num in lista if num>0)
print("La cantidad de números positivos en la lista es:",pos)

"""**Ejercicio 10:** Solicitar al usuario el ingreso de una cadena de texto e indicar cuántas vocales tiene en total."""

texto=str(input("Ingrese el texto: "))
voc=0
voc=sum(1 for letra in texto if letra=="a" or letra=="e" or letra=="i" or letra=="o" or letra=="u")
print("La cantidad de vocales en el texto es:",voc)

"""**Ejercicio 11:** Dada una cantidad no conocida de números reales no nulos indicar cuántos positivos hay en la lista y cuantos números en total se ingresaron."""

lista=[]
num=1
while num!=0:
  num=float(input("Ingrese un número. Ingresar 0 cerrará la lista: "))
  if num==0:
    break
  lista.append(num)
pos=0
pos=sum(1 for num in lista if num>0)
total=len(lista)
print(f"La cantidad de números positivos en la lista es: {pos}")
print(f"La cantidad total de números ingresados es: {total8}")

"""**Ejercicio 12:** Introducir una cadena de caracteres e indicar si es un *palíndromo*. Una palabra palíndroma es aquella que se lee igual de izquierda a derecha y de derecha a izquierda."""

palabra=str(input("Ingrese una palabra para saber si es un palíndromo: "))
palabrainv=""
for caracter in palabra:
  palabrainv=caracter+palabrainv
if palabra==palabrainv:
  print(f"{palabra} es un palíndromo.")
else:
  print(f"{palabra} no es un palíndromo.")

"""**Ejercicio 13:** Escribir un algoritmo que almacene una cadena de texto que contenga una contraseña cualquiera. Luego debe ofrecer 3 intentos para el ingreso de una nueva cadena de texto. Cuando las contraseñas coincidan ya no
se deberá solicitar más ingresos y se mostrará un mensaje diciendo “FELICITACIONES”.

Además, deberá mostrar un mensaje advirtiendo “CONTRASEÑA BLOQUEADA” si falló todos los intentos. Piensa bien en la condición o valores que pueden indicar esa situación
"""

contra=str(input("Ingrese su nueva contraseña: "))
verif=str(input("Ingrese nuevamente la contraseña. Tiene 3 intentos: "))
if verif==contra:
  print("¡Felicitaciones!")
elif verif!=contra:
  verif=str(input("Intente nuevamente. Tiene 2 intentos: "))
  if verif==contra:
    print("¡Felicitaciones!")
  elif verif!=contra:
    verif=str(input("Intente nuevamente. Tiene 1 intento: "))
    if verif==contra:
      print("¡Felicitaciones!")
    else:
      print("Contraseña Bloqueada.")

"""**Ejercicio 14:** Introducir una cadena de caracteres e indicar si es un *palíndromo*. Una palabra palíndroma es aquella que se lee igual de izquierda a derecha y de derecha a izquierda."""

palabra=str(input("Ingrese una palabra para saber si es un palíndromo: "))
palabrainv=""
for caracter in palabra:
  palabrainv=caracter+palabrainv
if palabra==palabrainv:
  print(f"{palabra} es un palíndromo.")
else:
  print(f"{palabra} no es un palíndromo.")

"""**Ejercicio 15:** Escribir un programa que almacene las asignaturas de un curso
(por ejemplo, Matemáticas, Física, Química, Historia y Lengua) en una lista,
pregunte al usuario la nota que ha sacado en cada asignatura, y después mostrar
por pantalla con el mensaje: "En X sacó Y" donde X es la asignatura correspondiente e Y es la nota correspondiente a la asignatura.
"""

asignaturas=["Matemáticas","Física","Química","Historia","Lengua"]
calificaciones=[]
for materia in asignaturas:
  nota=int(input(f"Ingrese su nota en {materia}: "))
  calificaciones.append(nota)
for i in range(len(asignaturas)):
  print(f"En {asignaturas[i]} sacó {calificaciones[i]}.")

"""**Ejercicio 16:** Los alumnos de un curso se han dividido en dos grupos A y B de
acuerdo al sexo y el nombre. El grupo A está formado por las mujeres con un
nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo
B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo,
y muestre por pantalla el grupo que le corresponde.
"""

nombre=str(input("Ingrese su nombre: "))
sexo=str(input("Ingrese su sexo (H o M): "))
alfabetoM=["A","B","C","D","E","F","G","H","I","J","K","L"]
alfabetoH=["O","P","Q","R","S","T","U","V","W","X","Y","Z"]
if sexo=="M":
  for i in range(12):
    if nombre[0]==alfabetoM[i]:
      grupo="A"
      break
    else:
      grupo="B"
  print(f"Pertenece al grupo {grupo}.")
else:
  for i in range(12):
    if nombre[0]==alfabetoH[i]:
      grupo="A"
      break
    else:
      grupo="B"
  print(f"Pertenece al grupo {grupo}.")

"""**Ejercicio 17:** Un local de comida rápida ('ML') conocido de la ciudad ofrece
hamburguesas vegetarianas y no vegetarianas a sus clientes. Los ingredientes
para cada tipo aparecen a continuación:
*   **Ingredientes vegetarianos:** calabaza – soja
*   **Ingredientes no vegetarianos:** carne vacuna - carne de pollo

Escribir un programa que pregunte al usuario si quiere una hamburguesa
vegetariana o no, y en función de su respuesta le muestre un menú con los
ingredientes disponibles para que elija. Solo se puede elegir un ingrediente
además de la lechuga, queso y el tomate que están en todas las hamburguesas.
Al final se debe mostrar por pantalla si la hamburguesa elegida es vegetariana o
no y todos los ingredientes que lleva.
"""

print("¡Bienvenido a Restaurante ML!")
vege=str(input("Ingrese 1 para pedir una hamburgesa vegetariana, o 2 para pedir una hamburguesa NO vegetariana: "))
if vege=="1":
  print("Va a pedir una hamburguesa vegetariana.")
  ingr=str(input("Ingrese 1 para pedir una hamburguesa de Cabalaza, o 2 para pedir una hamburguesa de Soja: "))
  if ingr=="1":
    print("Su hamburguesa de Calabaza incluirá Lechuga, Queso y Tomate.")
  else:
    print("Su hamburguesa de Soja incluirá Lechuga, Queso y Tomate.")
else:
  print("Va a pedir una hamburguesa NO vegetariana.")
  ingr=str(input("Ingrese 1 para pedir una hamburguesa de Carne Vacuna, o 2 para pedir una hamburguesa de Carne de Pollo: "))
  if ingr=="1":
    print("Su hamburguesa de Carne Vacuna incluirá Lechuga, Queso y Tomate.")
  else:
    print("Su hamburguesa de Carne de Pollo incluirá Lechuga, Queso y Tomate.")